title: ISMRM Member-Initiated Tutorial  Cardiovascular MR
description: Tutorials and challenges
theme: jekyll-theme-cayman

<nav>
  <ul>
    <li><a href="index.html" class="current">Work</a></li>
    <li><a href="info.html">Info</a></li>
    <li><a href="blog.html">Blog</a></li>
  </ul>
</nav>
