title: ISMRM Member-Initiated Tutorial  Cardiovascular MR
description: Tutorials and challenges
theme: jekyll-theme-cayman
color:
  header: "#000"
  gradient_left: "#e53935"
  gradient_right: "#f57c00"

